https://huggingface.co/datasets/open-index/arctic

In [1]:
import pandas as pd

In [92]:
df = pd.read_parquet("base_dbs/reddit_21.parquet")
df

,author,subreddit,text,score,body_length,link_id,parent_id,year
0,spidy8334,SaldyrkinaOksana,http://beteshis.com/24075721/saldyrkina,8,39,t3_knx7w2,t3_knx7w2,2013
1,LaplaceZ,Hololive,Having fun yet?,3,15,t3_knqryp,t1_ghmg8uk,2013
2,[deleted],thothub,[removed],1,9,t3_ko10gf,t3_ko10gf,2013
3,clammmmmmnnm,memes,This is scary,1,13,t3_knhwzx,t3_knhwzx,2013
4,Abdulaziz0b,Izlam,"Same, we got Newroz as the third one for the K...",37,51,t3_kny4nh,t1_ghna7qr,2013
...,...,...,...,...,...,...,...,...
499995,suttonoutdoor,HolUp,"Some do others, myself included, couldn’t care...",1,184,t3_kntpki,t1_ghn6mv0,2013
499996,Sluthunting,DegradedCaptions,She has no choice 🤷🏻‍♂️,1,23,t3_knf6kb,t1_ghmlg5g,2013
499997,psan-th,Evernote,"I see, occurred the same thing with me this we...",1,295,t3_kk6jen,t1_gh8l7c5,2013
499998,wowthisguyoverhere,buildapcsales,Been waiting forever for the freaking 3 pack f...,1,163,t3_ko2b9n,t3_ko2b9n,2013
499999,grimysavage,2007scape,So sick dude! I recreated it on Xbox 1 a few m...,1,116,t3_knvp2z,t3_knvp2z,2013

In [93]:
df["year"] = 2021

In [94]:
df["year"]

0         2021
1         2021
2         2021
3         2021
4         2021
          ...
499995    2021
499996    2021
499997    2021
499998    2021
499999    2021
Name: year, Length: 500000, dtype: int64

In [95]:
df.drop(["created_at","created_utc","id","author_flair_text","distinguished"], axis=1, inplace=True)

KeyError: "['created_at', 'created_utc', 'id', 'author_flair_text', 'distinguished'] not found in axis"

In [96]:
df.columns

Index(['author', 'subreddit', 'text', 'score', 'body_length', 'link_id',
       'parent_id', 'year'],
      dtype='object')

In [97]:
df.rename(columns={"body":"text"}, inplace=True)

In [98]:
df.columns

Index(['author', 'subreddit', 'text', 'score', 'body_length', 'link_id',
       'parent_id', 'year'],
      dtype='object')

In [99]:
df.head(1)

,author,subreddit,text,score,body_length,link_id,parent_id,year
0,spidy8334,SaldyrkinaOksana,http://beteshis.com/24075721/saldyrkina,8,39,t3_knx7w2,t3_knx7w2,2021

In [100]:
df.to_parquet("base_dbs/reddit_21.parquet")

In [101]:
df = pd.read_parquet("base_dbs/reddit_21.parquet")
df.drop(["author","score","body_length","link_id","parent_id","subreddit"], axis=1, inplace=True)

In [102]:
df

                                                     text  year
0                 http://beteshis.com/24075721/saldyrkina  2021
1                                         Having fun yet?  2021
2                                               [removed]  2021
3                                           This is scary  2021
4       Same, we got Newroz as the third one for the K...  2021
...                                                   ...   ...
499995  Some do others, myself included, couldn’t care...  2021
499996                            She has no choice 🤷🏻‍♂️  2021
499997  I see, occurred the same thing with me this we...  2021
499998  Been waiting forever for the freaking 3 pack f...  2021
499999  So sick dude! I recreated it on Xbox 1 a few m...  2021

[500000 rows x 2 columns]

In [103]:
df["category"] = "reddit"

In [104]:
df = df.sample(n=5000, random_state=42).reset_index(drop=True)

In [106]:
df.shape

(5000, 3)

In [107]:
df.to_parquet("base_dbs/reddit_21_ready.parquet")

In [108]:
df0 = pd.read_parquet("base_dbs/reddit_07_ready.parquet")
df1 = pd.read_parquet("base_dbs/reddit_13_ready.parquet")
df2 = pd.read_parquet("base_dbs/reddit_21_ready.parquet")

In [109]:
df = pd.concat([df0, df1, df2])

In [112]:
import seaborn as sns

In [115]:
df.rename(columns={"year":"decade"},inplace=True)

In [1]:
df.to_parquet("base_dbs/reddit.parquet")

NameError: name 'df' is not defined

In [3]:
import pandas as pd
df = pd.read_parquet("../.idea/data/base_dbs/reddit.parquet")

In [4]:
df.rename(columns={"decade":"year"},inplace=True)
df["decade"] = (df["year"] // 10) * 10
df["category"] = "reddit"
df["language_type"] = "written"

In [5]:
df.head()

,text,year,category,decade,language_type
0,So you think a stupid site like stickam is per...,2007,reddit,2000,written
1,"It wasn't clear, but I meant ""Most of the peop...",2007,reddit,2000,written
2,[deleted],2007,reddit,2000,written
3,"There is, it's called viper...",2007,reddit,2000,written
4,Man its good to be gay! all I had to worry abo...,2007,reddit,2000,written

In [6]:
df.shape

(15000, 5)

In [7]:
import processor
processor.process_db(df.copy(), "reddit", filter=False)

Writing C:\Users\ADMIN\Desktop\code\magshimim_final\processed_dbs\reddit.parquet
Successfully saved to: C:\Users\ADMIN\Desktop\code\magshimim_final\processed_dbs\reddit.parquet

,text,year,category,decade,language_type,text_length
0,So you think a stupid site like stickam is per...,2007,reddit,2000,written,231
1,"It wasn't clear, but I meant ""Most of the peop...",2007,reddit,2000,written,202
2,[deleted],2007,reddit,2000,written,9
3,"There is, it's called viper...",2007,reddit,2000,written,30
4,Man its good to be gay! all I had to worry abo...,2007,reddit,2000,written,124
...,...,...,...,...,...,...
4995,I'm 64 in April. I'm living in my truck w/camp...,2021,reddit,2020,written,376
4996,Elon spent good money on hair plugs or transpl...,2021,reddit,2020,written,86
4997,&gt;Why pursue the fool's errand of stuffing m...,2021,reddit,2020,written,744
4998,"Now instead of being fucked, you'll be fucked ...",2021,reddit,2020,written,51
4999,"Answer: The year 2020 has been hard, and so th...",2021,reddit,2020,written,159